---
plugin:
  name: "okd-epfl-hubble-ui"
  description: "Hubble UI in an OpenShift dashboard tab"
  image: ""
  imagePullPolicy: IfNotPresent
  replicas: 2
  port: 9443
  securityContext:
    enabled: true
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  basePath: /
  certificateSecretName: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  patcherServiceAccount:
    create: true
    annotations: {}
    name: ""
  jobs:
    patchConsoles:
      enabled: true
      image: "registry.redhat.io/openshift4/ose-tools-rhel8@sha256:e44074f21e0cca6464e50cb6ff934747e0bd11162ea01d522433a1a1ae116103"
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
hubbleUI:
  image: ""
  imagePullPolicy: IfNotPresent
  replicas: 2
  hostname: ~
  backend:
    # As found in install/kubernetes/cilium/values.yaml in the Cilium source tree:
    image: quay.io/cilium/hubble-ui-backend:v0.13.0
    imagePullPolicy: IfNotPresent
    relayHostPort: hubble-relay.cilium-system.svc.cluster.local:80
hubbleAPI:
  accessList: ~
  tokenReflector:
     image: ~
     replicas: 1
     namespace: openshift-console
     hostname: ~    # Deduced from hubbleUI.hostname by default
     path: /api/token-reflector
