apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include ".labels" . | nindent 4 }}
data:
  frontend-config.json: |-
    {
      "iframeDomain": "https://{{ required "hubbleUI.hostname must be set" .Values.hubbleUI.hostname }}",
      "tokenReflectorURI": "https://{{ include ".tokenReflectorHostname" . }}/api/token-reflector/token"
    }
