apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-hubble-api
  labels:
    {{- include ".labels" . | nindent 4 }}
rules:
- verbs: ["create"]
  nonResourceURLs:
  - /api/ui.UI/GetEvents
  - /api/ui.UI/GetControlStream
