apiVersion: v1
kind: Service
metadata:
  name: hubble-ui-epfl
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include ".labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: hubble-ui-epfl
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
