apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-ui-epfl
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include ".labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.hubbleUI.replicas }}
  selector:
    matchLabels:
      app: hubble-ui-epfl
  template:
    metadata:
      labels:
        app: hubble-ui-epfl
    spec:
      automountServiceAccountToken: false
      containers:
      - name: hubble-ui
        image: {{ required "hubbleUI.image must be specified!" .Values.hubbleUI.image }}
        imagePullPolicy: {{ .Values.hubbleUI.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 8080
