apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubble-api-consumer
  labels:
    {{- include ".labels" . | nindent 4 }}
rules:
- verbs: ["GET"]
  nonResourceURLs:
  - /api/hubble-ui
