apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hubble-ui
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include ".labels" . | nindent 4 }}
spec:
  host: {{ required "hubbleUI.hostname must be set" .Values.hubbleUI.hostname }}
  to:
    kind: Service
    name: hubble-ui-epfl
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
