apiVersion: v1
kind: Service
metadata:
  name: hubble-api-proxy
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include ".labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: hubble-api-proxy
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
