apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hubble-ui-restricted-api
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include ".labels" . | nindent 4 }}
spec:
  host: {{ required "hubbleAPI.hostname must be set" .Values.hubbleAPI.hostname }}
  path: /api/
  to:
    kind: Service
    name: hubble-ui-restricted
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
